# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TagDesigner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TagDesigner
	pod 'Canvas'
    pod 'Firebase/Auth'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
  target 'TagDesignerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TagDesignerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
